<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerENcUe0a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerENcUe0a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerENcUe0a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerENcUe0a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerENcUe0a\App_KernelDevDebugContainer([
    'container.build_hash' => 'ENcUe0a',
    'container.build_id' => '2e03618d',
    'container.build_time' => 1675277821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerENcUe0a');
